---

- hosts: all
  become: true
  tasks:
  
  - name: install apache and php
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

#inventory file contains
#10.1.1.11=apache_package=apache2 php_package=libapache2-mod-php
#10.1.1.12=apache_package=apache2 php_package=libapache2-mod-php
#10.1.1.13=apache_package=apache2 php_package=libapache2-mod-php
#10.1.1.20=apache_package=httpd php_package=php

